### ISSUE TITLE
Error: Whoops. Looks like this page doesn't exist.

### ISSUE THREAD

**Issue by ybizeul** [ryanlelek/Raneto#296] opened 2019-04-08 20:55 UTC
Anytime one tries _Edit_ in the _Actions_ button on a page that is not the page referenced to in the URL, you get this exception :

```
Error: Whoops. Looks like this page doesn't exist.
```

It happens on the root of the web site for example, where list of the md files is displayed on the center :

![Screenshot 2019-04-08 at 22 54 48](https://user-images.githubusercontent.com/182035/55756249-5c5d9b00-5a51-11e9-9920-e8f59f62d92f.png)

**Comment by ryanlelek** [comment] 2021-05-10 02:55
Yes, is this still happening for you?
The Index path (/) does give me that error. However, the intent is to automatically generate the Index page and not allow it to be manual (at this time).

**Comment by ryanlelek** [comment] 2021-05-10 02:56
#288 related

**Comment by ybizeul** [comment] 2021-05-22 15:19
I moved on since opening that bug and not using Raneto, you can close the issue.

**Comment by dkebler** [comment] 2021-06-19 01:42
Just spun up Renato and well, I'm getting error.  The url generated from the action/edit link is simply `http://localhost:3000/edit` no matter what page I attempt to edit.

Now it doesn't do this when I run the example site from within the cloned Renato repo.  But if i pull out the example folder, do and npm install, edit the default config a bit and then edit the server.js to get renato from the dependencies well then this issue arises.   Obviously something is not pointing to the right place.   THe console does not show any other debug errors.  So I'll need some assistance to track down why my install is not working.   BTW I can make a new page so that's working (I just can't afterwards edit it)

**Comment by dkebler** [comment] 2021-06-19 05:26
The example needs to be updated to `0.17.0` and the issue is resolved.  It had an older version.  Also gulp needs to be added to dev dependencies in order to get npm install to complete.  so package.json for the example should be

```
{
  "name": "raneto-example",
  "version": "1.0.0",
  "description": "",
  "main": "config.default.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node ./server.js"
  },
  "author": "Ryan Lelek <ryanlelek@gmail.com>",
  "license": "ISC",
  "dependencies": {
    "debug": "4.3.1",
    "raneto": "0.17.0"
  },
  "devDependencies": {
    "gulp": "^4.0.2"
  }
}
```

I'd close this but I didn't open it so I can't.

**Comment by ryanlelek** [comment] 2022-08-12 05:35
Thank you for investigating @dkebler 
Closing issue to cleanup

**Closed by ryanlelek** 2022-08-12 05:35 UTC
