### ISSUE TITLE
How to show the png images in the page?

### ISSUE THREAD

**Issue by zazaji** [ryanlelek/Raneto#359] opened 2021-07-04 01:26 UTC
The md file name that  contains dot (eg. 1.1-preface.md) , can't be opened correctly .

**Comment by ryanlelek** [comment] 2022-08-12 05:21
Hi @zazaji 
The title of the issue is different than the main text.

To show PNG images (or other images) in the page, you'll need to use Markdown syntax
`![My PNG Image Description](https://www.example.com/myimage.png)` or
For more details, [see this Markdown guide](https://www.markdownguide.org/cheat-sheet)

If you wish to host the image locally, there is not a way in the `content/` directory, which would make sense.
Instead, put it in the `themes/default/public/` directory for now.
(This should be fixed in a future version)
---

Having periods in file names is already filed on #317 
So follow that issue for more details

**Comment by ryanlelek** [comment] 2022-08-12 05:25
Please follow the uploading of images and other files on this new issue #372

---

Closing this issue.
Please open a new issue for any questions or requests you have.
Thanks for understanding while we clean up older issues in the repo.

**Closed by ryanlelek** 2022-08-12 05:25 UTC
Labels: enhancement, priority
