### ISSUE TITLE
Translation ignored

### ISSUE THREAD

**Issue by jci** [ryanlelek/Raneto#257] opened 2018-03-22 20:01 UTC
Hi,

seems that the translation for "es" (Spanish") is being ignored when following a page. On the main page "Main Articles" is shown as "Articulos Principales", which is correct. But when reading a page, the table of contents on the left shows "Main Articles". So it seems that the translation is ignored.

Kind regards,
--j

**Comment by ryanlelek** [comment] 2022-08-12 11:16
Hi @jci
Thank you for the report.
I was not able to reproduce the "Main Articles" issue.
But there are some places where translations don't take effect.

This is similar to what you mentioned and I'll add it to our Roadmap (see link above this comment).
I'll close this issue but we can continue the conversation there

**Closed by ryanlelek** 2022-08-12 11:16 UTC
Labels: bug, ready, qa
